/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddPost: typeof import('./components/AddPost.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    CareerCard: typeof import('./components/careerCard.vue')['default']
    Chat: typeof import('./components/chat.vue')['default']
    CommentComponent: typeof import('./components/commentComponent.vue')['default']
    CommentsComponent: typeof import('./components/commentsComponent.vue')['default']
    CommonCard: typeof import('./components/commonCard.vue')['default']
    CulturalPostCard: typeof import('./components/culturalPostCard.vue')['default']
    CulturalTypeCard: typeof import('./components/culturalTypeCard.vue')['default']
    EditCareerQuiz: typeof import('./components/editCareerQuiz.vue')['default']
    Editor: typeof import('./components/editor.vue')['default']
    EditorComponent: typeof import('./components/editorComponent.vue')['default']
    EditPsychologicalQuiz: typeof import('./components/editPsychologicalQuiz.vue')['default']
    EditPsychologicalTest: typeof import('./components/editPsychologicalTest.vue')['default']
    EditQuiz: typeof import('./components/editQuiz.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MessageComponent: typeof import('./components/messageComponent.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    PostCard: typeof import('./components/postCard.vue')['default']
    PostCardLite: typeof import('./components/postCard-lite.vue')['default']
    Radio: typeof import('./components/radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestComponent: typeof import('./components/testComponent.vue')['default']
    UserStatus: typeof import('./components/UserStatus.vue')['default']
  }
}
