/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/career': RouteRecordInfo<'/admin/career', '/admin/career', Record<never, never>, Record<never, never>>,
    '/admin/post': RouteRecordInfo<'/admin/post', '/admin/post', Record<never, never>, Record<never, never>>,
    '/admin/psychological': RouteRecordInfo<'/admin/psychological', '/admin/psychological', Record<never, never>, Record<never, never>>,
    '/admin/type': RouteRecordInfo<'/admin/type', '/admin/type', Record<never, never>, Record<never, never>>,
    '/admin/user': RouteRecordInfo<'/admin/user', '/admin/user', Record<never, never>, Record<never, never>>,
    '/sys': RouteRecordInfo<'/sys', '/sys', Record<never, never>, Record<never, never>>,
    '/sys/': RouteRecordInfo<'/sys/', '/sys', Record<never, never>, Record<never, never>>,
    '/sys/career': RouteRecordInfo<'/sys/career', '/sys/career', Record<never, never>, Record<never, never>>,
    '/sys/cultural': RouteRecordInfo<'/sys/cultural', '/sys/cultural', Record<never, never>, Record<never, never>>,
    '/sys/culturalPost': RouteRecordInfo<'/sys/culturalPost', '/sys/culturalPost', Record<never, never>, Record<never, never>>,
    '/sys/culturalPosts': RouteRecordInfo<'/sys/culturalPosts', '/sys/culturalPosts', Record<never, never>, Record<never, never>>,
    '/sys/details': RouteRecordInfo<'/sys/details', '/sys/details', Record<never, never>, Record<never, never>>,
    '/sys/post': RouteRecordInfo<'/sys/post', '/sys/post', Record<never, never>, Record<never, never>>,
    '/sys/posts': RouteRecordInfo<'/sys/posts', '/sys/posts', Record<never, never>, Record<never, never>>,
    '/sys/profile': RouteRecordInfo<'/sys/profile', '/sys/profile', Record<never, never>, Record<never, never>>,
    '/sys/psychological': RouteRecordInfo<'/sys/psychological', '/sys/psychological', Record<never, never>, Record<never, never>>,
    '/sys/schedule': RouteRecordInfo<'/sys/schedule', '/sys/schedule', Record<never, never>, Record<never, never>>,
    '/sys/test': RouteRecordInfo<'/sys/test', '/sys/test', Record<never, never>, Record<never, never>>,
  }
}
